import type { InputMode, ProcessResponse } from "@/lib/schema";

type DemoSafeParams = {
  inputMode: InputMode;
  transcript: string;
  requestId: string;
};

function getSentences(text: string) {
  return text
    .split(/(?<=[.!?])\s+/)
    .map((line) => line.trim())
    .filter(Boolean);
}

function buildSummary(transcript: string) {
  const sentences = getSentences(transcript);
  if (!sentences.length) {
    return "Transcript received. No summary content was available.";
  }

  return sentences.slice(0, 2).join(" ");
}

function toTaskLine(sentence: string) {
  const clean = sentence.replace(/^\s*(please|kindly)\s+/i, "").trim();
  if (!clean) {
    return "";
  }

  if (
    /^(follow|send|schedule|share|prepare|update|create|review|confirm|draft|book|call|email|sync|investigate|deploy|monitor|document|close|assign)\b/i.test(
      clean,
    )
  ) {
    return clean;
  }

  return `Follow up: ${clean}`;
}

function buildTasks(transcript: string) {
  const sentences = getSentences(transcript);
  const requestSentences = sentences.filter((sentence) =>
    /\b(please|need to|can you|could you|schedule|send|prepare|share|assign|update|create|must)\b/i.test(
      sentence,
    ),
  );

  const mapped = requestSentences.map((sentence) => toTaskLine(sentence)).filter(Boolean);
  if (mapped.length > 0) {
    return mapped.slice(0, 6);
  }

  return [];
}

function buildEmailDraft(summary: string, tasks: string[]) {
  const taskBody = tasks.length
    ? tasks.map((task, index) => `${index + 1}. ${task}`).join("\n")
    : "No explicit action items were detected in the transcript.";

  return [
    "Subject: Transcript Follow-up",
    "",
    summary,
    "",
    "Proposed action items:",
    taskBody,
    "",
    "Please review before sending.",
  ].join("\n");
}

export function buildDemoSafeModelOutput(params: DemoSafeParams): ProcessResponse {
  const summary = buildSummary(params.transcript);
  const taskList = buildTasks(params.transcript);
  const emailDraft = buildEmailDraft(summary, taskList);
  const now = new Date().toISOString();

  return {
    inputMode: params.inputMode,
    transcript: params.transcript,
    summary,
    actions: {
      taskList,
      emailDraft,
    },
    intelligence: {
      topics: ["support", "general"],
      entities: [],
      urgency: "low",
      sentiment: "neutral",
      openLoops: [],
    },
    auditTrail: [
      { step: "capture", timestamp: now, details: "Captured for demo-safe mode." },
      {
        step: "transcribe",
        timestamp: now,
        details: "Transcript came from client-provided text.",
      },
      {
        step: "extract",
        timestamp: now,
        details: "Summary/tasks generated by deterministic demo-safe logic.",
      },
      { step: "draft", timestamp: now, details: "Email draft generated locally." },
      { step: "safety_check", timestamp: now, details: "Demo-safe output validated." },
    ],
    meta: {
      requestId: params.requestId,
      model: "demo-safe-local-v1",
      latencyMs: 1,
      validation: "passed" as const,
      fallbackUsed: true,
      approvalRequired: false,
    },
  };
}

