#!/usr/bin/env bash
# generate-compliance-report.sh — Generate a point-in-time compliance report
# Usage: bash scripts/github-cli/generate-compliance-report.sh [output-file]
# Output: Markdown compliance report based on current register state

set -euo pipefail

REPO="${GITHUB_REPO:-$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || echo "unknown/repo")}"
DATE=$(date -u +%Y-%m-%d)
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
OUTPUT="${1:-reports/compliance-${DATE}.md}"

mkdir -p "$(dirname "$OUTPUT")"

echo "Generating compliance report → $OUTPUT"

node - << SCRIPT > "$OUTPUT"
const fs = require('fs');

const compliance = JSON.parse(fs.readFileSync('.black-vault/ComplianceLedger.json', 'utf8'));
const findings = JSON.parse(fs.readFileSync('.black-vault/FindingsRegister.json', 'utf8'));
const risks = JSON.parse(fs.readFileSync('.black-vault/RiskRegister.json', 'utf8'));
const metrics = JSON.parse(fs.readFileSync('.black-vault/MetricsLedger.json', 'utf8'));

const latest = metrics.metrics[metrics.metrics.length - 1];
const openFindings = findings.findings.filter(f => f.status !== 'VERIFIED');
const openRisks = risks.risks.filter(r => r.status === 'OPEN');
const passControls = compliance.controls.filter(c => c.status === 'PASS').length;
const totalControls = compliance.controls.length;

const date = new Date().toISOString().slice(0, 10);
const commit = process.env.COMMIT || '${COMMIT}';

console.log(\`# Compliance Report — \${date}

**Repo**: ${REPO}
**Commit**: \${commit}
**Protocol**: PROJECT_OPS_V13_BLACK_VAULT_ENTERPRISE

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Controls Passing | \${passControls}/\${totalControls} |
| Open Findings | \${openFindings.length} |
| Open Risks | \${openRisks.length} |
| Tests Passing | \${latest?.gates?.G4_test_count || 'N/A'} |
| Coverage (lines) | \${latest?.gates?.G6_coverage_lines || 'N/A'}% |
| Last Audit | \${compliance.last_audit} |
| Next Audit | \${compliance.next_audit} |

---

## Control Status

| ID | Control | Status | Evidence |
|----|---------|--------|---------|
\${compliance.controls.map(c => \`| \${c.id} | \${c.control} | \${c.status === 'PASS' ? '✅ PASS' : '❌ FAIL'} | \${c.evidence} |\`).join('\\n')}

---

## Open Findings

\${openFindings.length === 0 ? '**None** — all findings verified.' : openFindings.map(f => \`- **\${f.id}** (\${f.severity}): \${f.category} at \\\`\${f.location}\\\`\`).join('\\n')}

---

## Open Risks

\${openRisks.length === 0 ? '**None** — all risks mitigated or accepted.' : openRisks.map(r => \`- **\${r.id}** (\${r.impact}): \${r.description}\\n  Mitigation: \${r.mitigation}\`).join('\\n\\n')}

---

## Gate Results

| Gate | Status | Value |
|------|--------|-------|
| G1 Build | \${latest?.gates?.G1_build || 'N/A'} | |
| G2 Lint | \${latest?.gates?.G2_lint || 'N/A'} | |
| G3 TypeCheck | \${latest?.gates?.G3_typecheck || 'N/A'} | |
| G4 Tests | \${latest?.gates?.G4_tests || 'N/A'} | \${latest?.gates?.G4_test_count || ''} tests |
| G6 Coverage | PASS | Lines: \${latest?.gates?.G6_coverage_lines || 'N/A'}%, Branches: \${latest?.gates?.G6_coverage_branches || 'N/A'}% |
| G7 Mutation | PARTIAL | rbac.ts: \${latest?.gates?.G7_mutation_rbac || 'N/A'}%, Overall: \${latest?.gates?.G7_mutation_overall || 'N/A'}% |
| G9 SAST | \${latest?.gates?.G9_sast || 'N/A'} | \${latest?.gates?.G9_findings || '0'} findings |
| G10 Secrets | \${latest?.gates?.G10_secrets || 'N/A'} | \${latest?.gates?.G10_secrets_found || '0'} secrets |

---

*Generated by scripts/github-cli/generate-compliance-report.sh*
*Protocol: PROJECT_OPS_V13_BLACK_VAULT_ENTERPRISE*
\`);
SCRIPT

echo "Report saved: $OUTPUT"
