#!/usr/bin/env bash
# publish-metrics-dashboard.sh — Generate and post a hardening metrics dashboard issue
# Usage: bash scripts/github-cli/publish-metrics-dashboard.sh

set -euo pipefail

REPO="${GITHUB_REPO:-$(gh repo view --json nameWithOwner -q .nameWithOwner)}"
DATE=$(date -u +%Y-%m-%d)

echo "Publishing metrics dashboard to $REPO"

# Generate dashboard body
BODY=$(node - << 'SCRIPT'
const fs = require('fs');

const metrics  = JSON.parse(fs.readFileSync('.black-vault/MetricsLedger.json', 'utf8'));
const findings = JSON.parse(fs.readFileSync('.black-vault/FindingsRegister.json', 'utf8'));
const risks    = JSON.parse(fs.readFileSync('.black-vault/RiskRegister.json', 'utf8'));
const artifacts= JSON.parse(fs.readFileSync('.black-vault/ArtifactsLedger.json', 'utf8'));

const latest     = metrics.metrics[metrics.metrics.length - 1];
const prev       = metrics.metrics.length > 1 ? metrics.metrics[metrics.metrics.length - 2] : null;
const openRisks  = risks.risks.filter(r => r.status === 'OPEN').length;
const openFinds  = findings.findings.filter(f => f.status !== 'VERIFIED').length;

function delta(curr, prev, key) {
  if (!prev || prev[key] == null || curr[key] == null) return '';
  const d = curr[key] - prev[key];
  return d >= 0 ? ` (+${d.toFixed(1)})` : ` (${d.toFixed(1)})`;
}

const g = latest?.gates || {};
const pg = prev?.gates || {};

const report = `## 📊 Hardening Dashboard — ${new Date().toISOString().slice(0,10)}

**Repo**: ${process.env.REPO || ''}
**Commit**: ${latest?.commit || 'N/A'}
**Protocol**: PROJECT_OPS_V13_BLACK_VAULT_ENTERPRISE

---

### Gate Summary

| Gate | Status | Value |
|------|--------|-------|
| G1 Build | ${g.G1_build || 'N/A'} | |
| G2 Lint | ${g.G2_lint || 'N/A'} | |
| G3 TypeCheck | ${g.G3_typecheck || 'N/A'} | |
| G4 Tests | ${g.G4_tests || 'N/A'} | ${g.G4_test_count || 'N/A'} tests |
| G6 Lines | ${g.G6_coverage_lines >= 75 ? 'PASS' : 'FAIL'} | ${g.G6_coverage_lines || 'N/A'}%${delta(g,pg,'G6_coverage_lines')} |
| G6 Branches | ${g.G6_coverage_branches >= 60 ? 'PASS' : 'FAIL'} | ${g.G6_coverage_branches || 'N/A'}%${delta(g,pg,'G6_coverage_branches')} |
| G7 Mutation (rbac) | ${g.G7_mutation_rbac >= 95 ? 'PASS' : 'PARTIAL'} | ${g.G7_mutation_rbac || 'N/A'}% |
| G7 Mutation (overall) | PARTIAL | ${g.G7_mutation_overall || 'N/A'}% |
| G9 SAST | ${g.G9_sast || 'N/A'} | ${g.G9_findings || '0'} findings |
| G10 Secrets | ${g.G10_secrets || 'N/A'} | ${g.G10_secrets_found || '0'} |
| G12 Container CRITICAL | PASS | ${g.G12_container_critical ?? 0} |
| G12 Container HIGH | PASS | ${g.G12_container_high ?? 0} |

---

### Findings & Risks

| Category | Count |
|----------|-------|
| Total findings | ${findings.summary.total} |
| Verified (closed) | ${findings.summary.verified} |
| Open findings | ${openFinds} |
| Open risks | ${openRisks} |

---

### Artifacts

| Artifact | Details |
|----------|---------|
${artifacts.artifacts.map(a => `| ${a.type} | ${a.tool || ''} ${a.format || ''} ${a.components ? `${a.components} components` : ''} |`).join('\n')}

---

*Auto-generated by scripts/github-cli/publish-metrics-dashboard.sh*
*Protocol: PROJECT_OPS_V13_BLACK_VAULT_ENTERPRISE*`;

console.log(report);
SCRIPT
)

# Close previous dashboard issues
PREV_ISSUES=$(gh issue list \
  --repo "$REPO" \
  --search "[DASHBOARD] in:title" \
  --state open \
  --json number \
  --jq '.[].number' 2>/dev/null || echo "")

for N in $PREV_ISSUES; do
  gh issue close "$N" --repo "$REPO" --comment "Superseded by new dashboard — $(date -u +%Y-%m-%d)" --silent 2>/dev/null || true
  echo "  Closed previous dashboard issue #$N"
done

# Create new dashboard issue
ISSUE_URL=$(gh issue create \
  --repo "$REPO" \
  --title "[DASHBOARD] Hardening Status — $DATE" \
  --body "$BODY" \
  --label "type:scan-task")

echo "Dashboard published: $ISSUE_URL"
